services:
  snileit:
    image: snipe/snipe-it:latest
    # ports:
    # - 8000:80
    volumes:
      - snipeit-data:/var/lib/snipeit
    links:
      - snipedb:snipedb
      - redis
    network:
      - snipeit

  db:
    container_name: db
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    # ports:
    # - 3306:3306
    network:
      - snipeit

volumes:
  mysql-data
  snipeit-data

networks:
  snipeit:
# Added to networks to allow for communicaiton between http-proxy and 
  backend:
    external: true
    name: http_proxy_backend

