version: '3.8'

services:
  snipeit:
    image: 'snipe/snipe-it:latest'
    # ports:
    # - 8000:80
    volumes:
      - snipeit-data:/var/lib/snipeit
        #links:
        #- snipedb:snipedb
        #- redis
    networks:
      - snipeit
      - proxy
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - MYSQL_USER=snipit
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=snipit
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306

      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${VIRTUAL_HOST}
      - APP_TIMEZONE=UTC
      - APP_LOCALE=en

      - MAIL_PORT_587_TCP_ADDR=${SMTP_SERVER}
      - MAIL_PORT_587_TCP_PORT=${SMTP_PORT}
      - MAIL_ENV_FROM_ADDR=${SNIPEIT_EMAIL}
      - MAIL_ENV_FROM_NAME=${SNIPEIT_EMAIL_NAME}
      - MAIL_ENV_ENCRYPTION=${SMTP_ENCRYPTION}
      - MAIL_ENV_USERNAME=${SNIPEIT_EMAIL_USERNAME}
      - MAIL_ENV_PASSWORD=${SNIPEIT_EMAIL_PASSWORD}

       - PHP_UPLOAD_LIMIT=100
  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    # ports:
    # - 3306:3306
    networks:
      - snipeit
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  mysql-data:
  snipeit-data:

networks:
  snipeit:
# Added to networks to allow for communicaiton between http-proxy and 
  proxy:
    external: true
    name: http-proxy_proxy

